INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('Legislative Branch', '0');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('Architect of the Capitol', '1');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('Capitol Police', '2');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('Library of Congress', '3');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('Government Publishing Office', '4');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('Government Accountability Office', '5');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('Congressional Budget Office', '8');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('Judicial Branch', '10');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('Executive Office of the President', '11');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('Department of Agriculture', '12');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('Department of Commerce', '13');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('Department of the Interior', '14');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('Department of Justice', '15');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('Department of Labor', '16');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('Department of the Navy', '17');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('United States Marine Corps', '17');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('Postal Service', '18');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('Department of State', '19');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('Department of the Treasury', '20');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('Department of the Army', '21');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('United States Tax Court', '23');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('Office of Personnel Management', '24');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('National Credit Union Administration', '25');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('Federal Retirement Thrift Investment Board', '26');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('Federal Communications Commission', '27');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('Social Security Administration', '28');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('Federal Trade Commission', '29');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('Nuclear Regulatory Commission', '31');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('Smithsonian Institution', '33');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('International Trade Commission', '34');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('Department of Veterans Affairs', '36');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('Equal Employment Opportunity Commission', '45');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('General Services Administration', '47');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('National Science Foundation', '49');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('Securities and Exchange Commission', '50');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('Federal Deposit Insurance Corporation', '51');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('Central Intelligence Agency', '56');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('Departement of the Air Force', '57');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('Railroad Retirement Board', '60');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('Consumer Product Safety Commission', '61');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('Office of Special Counsel', '62');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('Federal Maritime Commission', '65');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('Environmental Protection Agency', '68');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('Department of Transportation', '69');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('Department of Homeland Security', '70');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('Small Business Administration', '73');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('American Battle Monuments Commission', '74');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('Department of Health and Human Services', '75');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('National Aeronautics and Space Administration', '80');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('Neighborhood Reinvestment Corporation', '82');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('Export-Import Bank of the United States', '83');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('Department of Housing and Urban Development', '86');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('National Archives and Records Administration', '88');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('Department of Energy', '89');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('Selective Service System', '90');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('Department of Education', '91');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('Corps of Engineers--Civil Works', '96');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('Department of Defense', '97');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('Defense Nuclear Facilities Safety Board', '347');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('Merit Systems Protection Board', '389');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('National Capital Planning Commission', '394');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('National Endowment for the Arts', '417');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('National Labor Relations Board', '420');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('National Transportation Safety Board', '424');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('Office of Navajo and Hopi Indian Relocation', '435');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('United States Holocaust Memorial Museum', '456');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('Corporation for National and Community Service', '485');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('Federal Labor Relations Authority', '504');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('Court Services and Offender Supervision Agency for the District of Columbia', '511');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('Presidio Trust', '512');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('Broadcasting Board of Governors', '514');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('Federal Housing Finance Agency', '537');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('Northern Border Regional Commission', '573');
INSERT INTO `LMS`.`Agency` (`AgencyName`, `AgencyCode`) VALUES ('Bureau of Consumer Financial Protection', '581');
